const $=s=>document.querySelector(s);let file=null;const input=$('#videoInput'),video=$('#preview'),drop=$('#dropzone');
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2600)}
function log(t){$('#aiLog').innerHTML='<span>AI</span> '+t}
function loadVideo(f){if(!f||!f.type.startsWith('video/'))return toast('اختار ملف فيديو صحيح');file=f;$('#fileName').textContent=f.name;video.src=URL.createObjectURL(f);video.style.display='block';$('#emptyPreview').style.display='none';video.onloadedmetadata=()=>{$('#duration').textContent=new Date(video.duration*1000).toISOString().slice(14,19);};log('الفيديو جاهز للتحليل.');toast('تم تحميل الفيديو')}
input.onchange=e=>loadVideo(e.target.files[0]);drop.ondragover=e=>{e.preventDefault();drop.style.borderColor='#d9f76c'};drop.ondragleave=()=>drop.style.borderColor='';drop.ondrop=e=>{e.preventDefault();drop.style.borderColor='';loadVideo(e.dataTransfer.files[0])};
video.ontimeupdate=()=>{$('#progress').style.width=(video.currentTime/video.duration*100)+'%'};
function autoEdit(){if(!file)return toast('ارفع فيديو الأول');const style=$('#style').value;const bg=$('#bgMode').value;$('#status').innerHTML='<i></i> جاري التحليل';log('بيحلل الصوت والحركة ونقاط الكلام...');let i=0;const msgs=['اكتشاف المقاطع الهادية والقصات المناسبة...','تحديد لحظات التركيز للـ Smart Zoom...','تجهيز الترجمة العربية والتوقيت...','تطبيق إعدادات الخلفية والتأثيرات...'];const timer=setInterval(()=>{log(msgs[i++]);if(i===msgs.length){clearInterval(timer);finish(style,bg)}},650)}
function finish(style,bg){$('#status').innerHTML='<i></i> اكتمل';$('#score').textContent=(92+Math.floor(Math.random()*7))+'%';const names={clean:'Clean & Professional',social:'Fast Social',cinematic:'Cinematic'};log(`تم بناء خطة ${names[style]} مع ${bg==='blur'?'Blur للخلفية':bg==='studio'?'Studio Background':'الخلفية الأصلية'}.`);document.querySelectorAll('.step em').forEach(e=>e.textContent='AI Ready');toast('تم تجهيز المونتاج تلقائيًا ✓')}
$('#autoBtn').onclick=autoEdit;$('#autoSide').onclick=autoEdit;$('#exportTop').onclick=()=>{if(!file)return toast('ارفع فيديو الأول');toast('التصدير الكامل يحتاج محرك FFmpeg/خدمة معالجة — الواجهة والخطة جاهزين')};
$('#themeBtn').onclick=()=>{document.body.classList.toggle('light');$('#themeBtn').textContent=document.body.classList.contains('light')?'☀':'☾'};
document.querySelectorAll('.nav').forEach(n=>n.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));n.classList.add('active');toast(n.innerText.trim()+' — قريبًا')});
