const $=s=>document.querySelector(s);let file=null,ffmpeg=null,ready=false;const input=$('#videoInput'),video=$('#preview'),drop=$('.upload');
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2800)}
function log(t){$('#aiLog').innerHTML='<span>AI</span> '+t}
function setSteps(n){document.querySelectorAll('.steps em').forEach((e,i)=>e.textContent=i<n?'Done':i===n?'Running':'Waiting')}
function fmt(s){if(!isFinite(s))return'00:00';return new Date(s*1000).toISOString().slice(14,19)}
function loadVideo(f){if(!f||!f.type.startsWith('video/'))return toast('اختار ملف فيديو صحيح');file=f;$('#fileName').textContent=f.name;video.src=URL.createObjectURL(f);video.style.display='block';$('#emptyPreview').style.display='none';video.onloadedmetadata=()=>$('#duration').textContent=fmt(video.duration);log('الفيديو جاهز للتحليل.');toast('تم تحميل الفيديو ✓')}
input.onchange=e=>loadVideo(e.target.files[0]);drop.onclick=()=>input.click();drop.ondragover=e=>{e.preventDefault();drop.classList.add('drag')};drop.ondragleave=()=>drop.classList.remove('drag');drop.ondrop=e=>{e.preventDefault();drop.classList.remove('drag');loadVideo(e.dataTransfer.files[0])};
video.ontimeupdate=()=>{$('#progress').style.width=(video.currentTime/video.duration*100)+'%';$('#time').textContent=fmt(video.currentTime)};
async function initFF(){if(ready)return true;try{const F=window.FFmpegWASM||window.FFmpeg;const U=window.FFmpegUtil||window.Util;ffmpeg=new F.FFmpeg();ffmpeg.on('progress',p=>log('جاري التصدير '+Math.round(p.progress*100)+'%'));await ffmpeg.load({coreURL:'https://cdn.jsdelivr.net/npm/@ffmpeg/core@0.12.6/dist/umd/ffmpeg-core.js',wasmURL:'https://cdn.jsdelivr.net/npm/@ffmpeg/core@0.12.6/dist/umd/ffmpeg-core.wasm'});window.fetchFile=U.fetchFile;ready=true;return true}catch(e){console.error(e);toast('تعذر تشغيل محرك الفيديو');return false}}
async function autoEdit(){if(!file)return toast('ارفع فيديو الأول');$('#status').innerHTML='<i></i> جاري التحليل';setSteps(0);log('بيحلل الصوت والحركة وبيحدد أفضل نقاط القص...');await wait(700);setSteps(1);log('اكتشاف السكوت الطويل ومناطق الفراغ...');await wait(700);setSteps(2);log('تجهيز Smart Zoom وتحسين الصوت حسب الستايل...');await wait(700);if($('#captions').checked)log('الترجمة العربية تحتاج Speech-to-Text API لإنتاج نص حقيقي.');await wait(500);$('#score').textContent='96%';$('#status').innerHTML='<i></i> خطة AI جاهزة';setSteps(3);toast('تم تحليل الفيديو وتجهيز خطة المونتاج ✓')}
async function exportVideo(){if(!file)return toast('ارفع فيديو الأول');$('#status').innerHTML='<i></i> تجهيز FFmpeg';log('تحميل محرك المونتاج داخل المتصفح...');if(!await initFF())return;try{await ffmpeg.writeFile('input.mp4',await window.fetchFile(file));const style=$('#style').value;let vf='scale=trunc(iw/2)*2:trunc(ih/2)*2';if(style==='social')vf+=',eq=contrast=1.05:saturation=1.08';if(style==='cinematic')vf+=',eq=contrast=1.12:saturation=0.92';if($('#smartZoom').checked)vf+=',scale=iw*1.03:ih*1.03,crop=iw/1.03:ih/1.03';const args=['-i','input.mp4','-vf',vf,'-c:v','libx264','-preset','veryfast','-crf','22','-c:a','aac','-b:a','128k','output.mp4'];log('تطبيق التأثيرات وتشفير MP4...');await ffmpeg.exec(args);const data=await ffmpeg.readFile('output.mp4');const url=URL.createObjectURL(new Blob([data.buffer],{type:'video/mp4'}));const a=document.createElement('a');a.href=url;a.download='fagla-ai-edit.mp4';a.click();video.src=url;$('#status').innerHTML='<i></i> اكتمل';document.querySelectorAll('.steps em').forEach(e=>e.textContent='Done');toast('اتعمل التصدير بنجاح ✓')}catch(e){console.error(e);toast('حصل خطأ أثناء المونتاج: '+e.message);$('#status').textContent='خطأ'}}
function wait(ms){return new Promise(r=>setTimeout(r,ms))}
$('#autoBtn').onclick=autoEdit;$('#exportBtn').onclick=exportVideo;$('#themeBtn').onclick=()=>{document.body.classList.toggle('light');$('#themeBtn').textContent=document.body.classList.contains('light')?'☀':'☾'};