const $=s=>document.querySelector(s);let file=null,ffmpeg=null,ready=false,processing=false,job=null;const input=$('#videoInput'),video=$('#preview'),drop=$('.upload');
const wait=ms=>new Promise(r=>setTimeout(r,ms));
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2800)}
function log(t){$('#aiLog').innerHTML='<span>AI</span> '+t}
function fmt(s){if(!isFinite(s))return'00:00';return new Date(s*1000).toISOString().slice(14,19)}
function setSteps(n){document.querySelectorAll('.steps em').forEach((e,i)=>e.textContent=i<n?'Done':i===n?'Running':'Waiting')}
function loadVideo(f){if(!f||!f.type.startsWith('video/'))return toast('اختار ملف فيديو صحيح');file=f;job=null;$('#fileName').textContent=f.name;video.src=URL.createObjectURL(f);video.style.display='block';$('#emptyPreview').style.display='none';video.onloadedmetadata=()=>$('#duration').textContent=fmt(video.duration);log('الفيديو جاهز للتحليل.');toast('تم تحميل الفيديو ✓')}
input.onchange=e=>loadVideo(e.target.files[0]);drop.onclick=()=>input.click();drop.ondragover=e=>{e.preventDefault();drop.classList.add('drag')};drop.ondragleave=()=>drop.classList.remove('drag');drop.ondrop=e=>{e.preventDefault();drop.classList.remove('drag');loadVideo(e.dataTransfer.files[0])};
video.ontimeupdate=()=>{$('#progress').style.width=(video.currentTime/video.duration*100)+'%';$('#time').textContent=fmt(video.currentTime)};
async function uploadForAnalysis(){
  const form=new FormData();form.append('video',file);
  log('رفع الفيديو للسيرفر وتجهيز الصوت للتحليل...');
  const response=await fetch('/api/upload',{method:'POST',body:form});
  const data=await response.json().catch(()=>({}));
  if(!response.ok)throw new Error(data.error||`Upload failed (${response.status})`);
  job=data.job;
  return data;
}
async function initFF(){if(ready)return true;try{const{FFmpeg}=FFmpegWASM;ffmpeg=new FFmpeg();ffmpeg.on('progress',p=>log('تصدير الفيديو: '+Math.round(p.progress*100)+'%'));await ffmpeg.load({coreURL:'https://cdn.jsdelivr.net/npm/@ffmpeg/core@0.12.6/dist/umd/ffmpeg-core.js',wasmURL:'https://cdn.jsdelivr.net/npm/@ffmpeg/core@0.12.6/dist/umd/ffmpeg-core.wasm'});ready=true;return true}catch(e){console.error(e);toast('تعذر تشغيل محرك الفيديو');return false}}
function buildFilters(){const style=$('#style').value,bg=$('#bgMode').value;let vf='scale=trunc(iw/2)*2:trunc(ih/2)*2';if(style==='social')vf+=',eq=contrast=1.06:saturation=1.10:brightness=0.01';if(style==='cinematic')vf+=',eq=contrast=1.12:saturation=0.90:brightness=-0.01';if(style==='clean')vf+=',eq=contrast=1.03:saturation=1.03';if($('#smartZoom').checked)vf+=',scale=iw*1.035:ih*1.035,crop=iw/1.035:ih/1.035';if(bg==='blur')vf+=',boxblur=2:1';return vf}
async function autoEdit(){if(processing)return;if(!file)return toast('ارفع فيديو الأول');processing=true;$('#status').innerHTML='<i></i> جاري التحليل';setSteps(0);try{await uploadForAnalysis();setSteps(1);log($('#cutSilence').checked?'تم استخراج WAV 16kHz mono — جاهز لتحليل السكوت.':'تم استخراج WAV 16kHz mono. قص السكوت معطل.');await wait(500);setSteps(2);log('الـ backend جهز مرحلة الصوت. Whisper وتحليل السكوت الحقيقيين لسه المرحلة التالية.');await wait(400);if($('#captions').checked)log('الترجمة العربية مفعلة — ربط Whisper يأتي بعد نجاح اختبار الـ upload.');await wait(300);$('#score').textContent='—';$('#status').innerHTML='<i></i> تم تجهيز الفيديو';setSteps(2);toast(`تم رفع الفيديو وتجهيز الصوت ✓ Job: ${job.id}`)}catch(e){console.error(e);$('#status').textContent='حصل خطأ';toast('فشل تحليل الفيديو: '+e.message)}finally{processing=false}}
async function exportVideo(){if(processing)return;if(!file)return toast('ارفع فيديو الأول');processing=true;$('#status').innerHTML='<i></i> تشغيل محرك الفيديو';log('تحميل محرك FFmpeg داخل المتصفح...');if(!await initFF()){processing=false;return}try{const{fetchFile}=FFmpegUtil;await ffmpeg.writeFile('input.mp4',await fetchFile(file));const vf=buildFilters();const af=$('#audioFix').checked?'loudnorm=I=-16:TP=-1.5:LRA=11':'anull';const args=['-i','input.mp4','-vf',vf,'-af',af,'-c:v','libx264','-preset','veryfast','-crf','22','-c:a','aac','-b:a','160k','-movflags','+faststart','output.mp4'];setSteps(2);log('تطبيق المؤثرات وتحسين الصوت...');await ffmpeg.exec(args);setSteps(3);const data=await ffmpeg.readFile('output.mp4');const url=URL.createObjectURL(new Blob([data.buffer],{type:'video/mp4'}));const a=document.createElement('a');a.href=url;a.download='fagla-ai-edit.mp4';a.click();video.src=url;$('#status').innerHTML='<i></i> اكتمل';document.querySelectorAll('.steps em').forEach(e=>e.textContent='Done');toast('اتعمل التصدير بنجاح ✓')}catch(e){console.error(e);$('#status').textContent='حصل خطأ';toast('حصل خطأ أثناء التصدير: '+e.message)}finally{processing=false}}
$('#autoBtn').onclick=autoEdit;$('#exportBtn').onclick=exportVideo;$('#themeBtn').onclick=()=>{document.body.classList.toggle('light');$('#themeBtn').textContent=document.body.classList.contains('light')?'☀':'☾'};
